---
title: Analysis of GEEP Jesus Combo ACT CD8 TIL, first batch
author: "M. Andreatta <massimo.andreatta at unil.ch> and S. Carmona <santiago.carmona at unil.ch>"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.Jesus.1120.html'))})
#output: html_notebook
---

```{r}
renv::restore()
library(remotes)
#install_github("carmonalab/UCell", ref="v1.1")
#install_github("carmonalab/scGate",ref="v1.0.0")
#install_github("carmonalab/ProjecTILs",ref="v2.0.0")
#install_github("ncborcherding/scRepertoire",ref="3f676c5beca96878585811ed557813dafd241e48") # version 1.3.2

```


```{r message=FALSE}
library(Seurat)
library(ggplot2)
library(scRepertoire)
library(ProjecTILs)
#library(ggpubr)
```


```{r message=FALSE}
source("FirstBatch_functions.R")
```

# Raw data in available in https://drive.switch.ch/index.php/s/ef1YzkMDkparotX
```{r}
data.seurat <- Read10X("~/switchdrive/CSI/data/Jesus_2019/Jesus_all/")
data.seurat <- CreateSeuratObject(counts = data.seurat, project = "JesusAll", min.cells = 3, min.features = 50)
data.seurat$Sample <- substring(colnames(data.seurat),18)
table(data.seurat$Sample)
metaData <- read.csv("~/switchdrive/CSI/data/Jesus_2019/Jesus_all/aggregation_csv.csv",as.is = T)
data.seurat$Timepoint <- factor(data.seurat$Sample, levels = c(1:8), labels=metaData$grp)
data.seurat$Treatment <- factor(data.seurat$Sample, levels = c(1:8), labels=metaData$treatment)
data.seurat$Sample <- factor(paste(data.seurat$Timepoint,data.seurat$Treatment,sep="-"))

data.seurat$SampleLabel <- data.seurat$Sample
table(data.seurat$SampleLabel)
```

Ribosomal and mitochondrial content
```{r}
data.seurat <- AddMetaData(data.seurat, metadata = PercentageFeatureSet(data.seurat, pattern = "^Rp[ls]"), col.name = "percent.ribo")
data.seurat <- AddMetaData(data.seurat, metadata = PercentageFeatureSet(data.seurat, pattern = "^mt-"), col.name = "percent.mito")
```

Filter out outliers & low quality cells
```{r fig.height= 10}
Idents(data.seurat) <- "Sample"
VlnPlot(data.seurat, features = c("nFeature_RNA", "nCount_RNA","percent.ribo","percent.mito"), ncol = 2, pt.size=0.01)

cutoffs <- list()
cutoffs[["percent.ribo"]] <- c(min=max(quantile(data.seurat$percent.ribo,probs=c(0.01)),5),max=min(quantile(data.seurat$percent.ribo,probs=c(0.99)),60))
cutoffs[["percent.mito"]] <- c(min=max(quantile(data.seurat$percent.mito,probs=c(0.01)),0),max=min(quantile(data.seurat$percent.mito,probs=c(0.99)),10))
cutoffs[["nFeature_RNA"]] <- c(min=max(quantile(data.seurat$nFeature_RNA,probs=c(0.01)),500),max=min(quantile(data.seurat$nFeature_RNA,probs=c(0.99)),6000))
cutoffs[["nCount_RNA"]] <- c(min=max(quantile(data.seurat$nCount_RNA,probs=c(0.01)),2000),max=min(quantile(data.seurat$nCount_RNA,probs=c(0.99)),40000))

print(cutoffs)

dim(data.seurat)

data.seurat <- subset(data.seurat, subset = nFeature_RNA > cutoffs[["nFeature_RNA"]]["min"] & nFeature_RNA < cutoffs[["nFeature_RNA"]]["max"] & 
                       nCount_RNA > cutoffs[["nCount_RNA"]]["min"] & nCount_RNA < cutoffs[["nCount_RNA"]]["max"] &
                       percent.ribo > cutoffs[["percent.ribo"]]["min"] &  percent.ribo < cutoffs[["percent.ribo"]]["max"] &
                    percent.mito > cutoffs[["percent.mito"]]["min"] & percent.mito < cutoffs[["percent.mito"]]["max"] )
dim(data.seurat)

Idents(data.seurat) <- "Sample"
VlnPlot(data.seurat, features = c("nFeature_RNA", "nCount_RNA","percent.ribo","percent.mito"), ncol = 2, pt.size=0.01)

```



```{r}
removeGenes <- unique(unique(unlist(scGate::genes.blacklist.default$Mm)))
length(removeGenes)
```


```{r}
VlnPlot(data.seurat, features = c("Ptprc", "Cd2","Cd8a","Pdcd1"), ncol = 2, pt.size=0.01)
data.seurat <- NormalizeData(data.seurat)
VlnPlot(data.seurat, features = c("Ptprc", "Cd2","Cd8a","Pdcd1"), ncol = 2, pt.size=0.01)
data.seurat <- FindVariableFeatures(data.seurat, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
length(data.seurat@assays$RNA@var.features)
data.seurat@assays$RNA@var.features <- data.seurat@assays$RNA@var.features[!data.seurat@assays$RNA@var.features %in% removeGenes]
```


```{r}
set.seed(12345)

data.seurat <- ScaleData(data.seurat, do.scale = TRUE, do.center = TRUE) 
data.seurat <- RunPCA(object = data.seurat, features = data.seurat@assays$RNA@var.features, ndims.print = 1:5, nfeatures.print = 10)

```




```{r}
ndim=10
data.seurat <- RunUMAP(data.seurat, reduction = "pca", dims = 1:ndim, seed.use=123, n.neighbors = 30, min.dist = 0.3)
```

```{r}
DimPlot(data.seurat, reduction = "umap", group.by = "SampleLabel") + ggtitle("UMAP by study")
```

```{r}
DimPlot(data.seurat, reduction = "umap", group.by = "Treatment") + ggtitle("UMAP by study")
```



```{r}
FeaturePlot(data.seurat,features=c("Ptprc","Spi1","H2-Aa","Cd19"),reduction = "umap",cols = c("lightgrey", "blue"))
FeaturePlot(data.seurat,features=c("Cd2","Cd8a","Cd8b1","Cd4"),reduction = "umap",cols = c("lightgrey", "blue"))
FeaturePlot(data.seurat,features=c("Mki67","Ncr1","Klra8","Fcer1g"),reduction = "umap",cols = c("lightgrey", "blue"))
FeaturePlot(data.seurat,features=qq(Ifitm2,Lgals3,AA467197,Hilpda),reduction = "umap",cols = c("lightgrey", "blue"),sort.cell = T)
FeaturePlot(data.seurat,features=qq(Bnip3,Ifitm3,Fcer1g,Spi1),reduction = "umap",cols = c("lightgrey", "blue"),sort.cell = T)
FeaturePlot(data.seurat,features=qq(Foxp3,Tyrobp,Csf1r,Cd14),reduction = "umap",cols = c("lightgrey", "blue"),sort.cell = T)

```
```{r}
scGateModels <- get_scGateDB()
data.seurat <- scGate(data.seurat, scGateModels$mouse$generic$CD8T, additional.signatures = list("G1S"=scGate::genes.blacklist.default$Mm$cellCycle.G1S, "G2M"=scGate::genes.blacklist.default$Mm$cellCycle.G2M))
plot_levels(data.seurat)
```

```{r}
table(data.seurat$is.pure,data.seurat$Sample)
data.seurat.CD8 <- subset(data.seurat, subset=is.pure=="Pure")
```

Remove cycling cells, not interesting
```{r}
hist(data.seurat.CD8$G1S_UCell)
hist(data.seurat.CD8$G2M_UCell)
#data.seurat.CD8 <- subset(data.seurat.CD8, subset=G1S_UCell < 0.1 & G2M_UCell < 0.1)
```

```{r}
table(data.seurat.CD8$SampleLabel)
Idents(data.seurat.CD8) <- "SampleLabel"
set.seed(123)
data.seurat.CD8 <- subset(data.seurat.CD8, downsample = 600)
data.seurat.CD8$SampleLabel <- factor(data.seurat.CD8$SampleLabel)
table(data.seurat.CD8$SampleLabel)
```


```{r}
set.seed(12345)
data.seurat.CD8 <- FindVariableFeatures(data.seurat.CD8, selection.method = "vst", nfeatures = 1000, verbose = FALSE)
length(data.seurat.CD8@assays$RNA@var.features)
data.seurat.CD8@assays$RNA@var.features <- data.seurat.CD8@assays$RNA@var.features[!data.seurat.CD8@assays$RNA@var.features %in% removeGenes]
length(data.seurat.CD8@assays$RNA@var.features)
```

```{r}
set.seed(12345)
data.seurat.CD8 <- ScaleData(data.seurat.CD8, do.scale = TRUE, do.center = TRUE) 
data.seurat.CD8 <- RunPCA(object = data.seurat.CD8, features = data.seurat.CD8@assays$RNA@var.features, ndims.print = 1:5, nfeatures.print = 10)
ndim=30
data.seurat.CD8 <- RunUMAP(data.seurat.CD8, reduction = "pca", dims = 1:ndim, seed.use=123,min.dist = 0.2)
```

```{r}
#DimPlot(data.seurat.CD8, reduction = "umap", group.by = "cycling") + ggtitle("UMAP by study")
DimPlot(data.seurat.CD8, reduction = "umap", group.by = "Treatment") + ggtitle("UMAP by study")
DimPlot(data.seurat.CD8, reduction = "umap", group.by = "SampleLabel") + ggtitle("UMAP by study")
```



```{r}
FeaturePlot(object = data.seurat.CD8, features = qq(Tcf7,Pdcd1,Havcr2,Tox,Gzmb,Gzmk,Gzmc,Gzma,Mki67),order = T)
FeaturePlot(object = data.seurat.CD8, features = qq(Tcf7,Tox,Gzmc,Gzmk),order = T)
```


```{r}
set.seed(12345)

data.seurat.CD8 <- FindNeighbors(data.seurat.CD8, reduction = "pca", dims = 1:ndim)
data.seurat.CD8  <- FindClusters(data.seurat.CD8, resolution = 0.3)

data.seurat.CD8$cluster <- factor(data.seurat.CD8@active.ident)
data.seurat.CD8$cluster.lab <- factor(data.seurat.CD8$cluster,levels = c(1,0,3,2,4),labels = c("C1","C2","C3","C4","C5"))

clusterColors <- c("#F8766D","#A58AFF","#FF00FF","#53B400","#C49A00")
names(clusterColors) <- c("C1","C2","C3","C4","C5") 


DimPlot(data.seurat.CD8, reduction = "umap", group.by = "cluster.lab", cols = clusterColors) + ggtitle("UMAP by study") + theme(aspect.ratio = 1)

ggsave("pdf/unsup.umap.clusters.annot.pdf",width = 5, height = 5)
```

```{r}
facsMarkers <- qq(Mki67,Sell,Il7r,Tcf7,Lef1,Xcl1,Il2ra,Id2,Tnfrsf9,Gzmk,Gzma,Gzmb,Gzmc,Tox,Pdcd1,Lag3,Tigit,Havcr2,Entpd1)
Idents(data.seurat.CD8) <- factor(data.seurat.CD8$cluster.lab)
DotPlot(data.seurat.CD8, features = (facsMarkers), cols= "RdYlGn") + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
dir.create("./pdf")
ggsave("pdf/allSamples.DotPlot.clusters.pdf",width = 8, height = 3)


facsMarkers <- qq(Mki67,Sell,Il7r,Tcf7,Lef1,Klrg1,Cx3cr1,Gzmk,Gzma,Gzmb,Gzmc,Tox,Pdcd1,Lag3,Havcr2,Entpd1)

VlnPlot(data.seurat.CD8, features = (facsMarkers),stack = T, flip = T, fill.by = "ident", cols = clusterColors)

ggsave("pdf/allSamples.VlnPlot.clusters.pdf",width = 5, height = 5)


#2 cols
facsMarkers <- qq(Sell,Il7r,Tcf7,Lef1,Klrg1,Cx3cr1,Il2ra,Tnfrsf9,Id2,Nfatc1,Batf,
                  Gzmk,Gzma,Gzmb,Gzmc,Xcl1,Tox,Pdcd1,Lag3,Havcr2,Entpd1,Mki67)

a <- VlnPlot(data.seurat.CD8, features = (facsMarkers[1:11]),stack = T, flip = T, fill.by = "ident", cols = clusterColors) + 
  theme(legend.position = "none", axis.title.x = element_blank()) 

b <- VlnPlot(data.seurat.CD8, features = (facsMarkers[12:22]),stack = T, flip = T, fill.by = "ident", cols = clusterColors) + 
  theme(axis.title = element_blank()) 

a | b

ggsave("pdf/allSamples.VlnPlot.clusters.2col.pdf",width = 8, height = 4)

#3 cols
facsMarkers <- qq(Sell,Il7r,Tcf7,Lef1,Klrg1,Cx3cr1,Il2ra,Tnfrsf9,Id2,
                  Gzmk,Gzma,Gzmb,Gzmc, Ccl3, Ccl4, Ccl5, Nfatc1,Batf, 
                  Pdcd1,Lag3,Havcr2,Entpd1, Tox, Xcl1, Nr4a1, Nr4a2, Nr4a3, Mki67)

a <- VlnPlot(data.seurat.CD8, features = (facsMarkers[1:9]),stack = T, flip = T, fill.by = "ident", cols = clusterColors) + 
  theme(legend.position = "none", axis.title.x = element_blank()) 

b <- VlnPlot(data.seurat.CD8, features = (facsMarkers[10:18]),stack = T, flip = T, fill.by = "ident", cols = clusterColors) + 
  theme(axis.title = element_blank(), legend.position = "none", axis.title.x = element_blank()) 

c <- VlnPlot(data.seurat.CD8, features = (facsMarkers[19:28]),stack = T, flip = T, fill.by = "ident", cols = clusterColors) + 
  theme(axis.title = element_blank()) 

a | b | c

ggsave("pdf/allSamples.VlnPlot.clusters.3col.pdf",width = 9, height = 4)

```



```{r, fig.width=3, fig.height=3, fig.asp=0.6}
library(cowplot)
ggplot(data.frame(data.seurat.CD8@reductions$umap@cell.embeddings), aes(x=UMAP_1,y=UMAP_2)) +
       geom_point(aes(color=data.seurat.CD8@meta.data$cluster.lab),alpha=0.4, size=2) +
        geom_density_2d(data=data.frame(data.seurat.CD8@reductions$umap@cell.embeddings[data.seurat.CD8@meta.data$SampleLabel=="T1-combo",]),     
                        mapping=aes(x=UMAP_1,y=UMAP_2),color="black", n=100, h=2, size=0.5) + guides(color=guide_legend(title="CD8 state")) +
          ggtitle("Combo T1") + scale_colour_manual(values=clusterColors) + 
         theme_cowplot() + NoLegend() + 
          theme(aspect.ratio = 1, legend.position="right",
                axis.title=element_blank(),
                axis.text=element_blank(),
                axis.ticks=element_blank())

ggsave("pdf/unsup.umap.cluster.comboT1.countour.pdf",width = 5,height = 5)
```

```{r, fig.width=3, fig.height=3, fig.asp=0.6}
ggplot(data.frame(data.seurat.CD8@reductions$umap@cell.embeddings), aes(x=UMAP_1,y=UMAP_2)) + 
  geom_point(aes(color=data.seurat.CD8@meta.data$cluster.lab),alpha=0.4, size=2) + 
  geom_density_2d(data=data.frame(data.seurat.CD8@reductions$umap@cell.embeddings[data.seurat.CD8@meta.data$SampleLabel=="T2-combo",]), 
                  mapping=aes(x=UMAP_1,y=UMAP_2),color="black",n=100,h=2, size=1) + guides(color=guide_legend(title="CD8 state")) + ggtitle("Combo T2") + scale_colour_manual(values=clusterColors) + theme_cowplot() + NoLegend() + theme(aspect.ratio = 1, legend.position="right",
                axis.title=element_blank(),
                axis.text=element_blank(),
                axis.ticks=element_blank())

ggsave("pdf/unsup.umap.cluster.comboT2.countour.pdf",width = 5,height = 5)
```

```{r, fig.width=3, fig.height=3, fig.asp=0.6}
ggplot(data.frame(data.seurat.CD8@reductions$umap@cell.embeddings), aes(x=UMAP_1,y=UMAP_2)) + 
  geom_point(aes(color=data.seurat.CD8@meta.data$cluster.lab),alpha=0.4, size=2) + 
  geom_density_2d(data=data.frame(data.seurat.CD8@reductions$umap@cell.embeddings[data.seurat.CD8@meta.data$SampleLabel=="T3-combo",]), 
                  mapping=aes(x=UMAP_1,y=UMAP_2),color="black",n=100,h=2, size=1) + guides(color=guide_legend(title="CD8 state")) + ggtitle("Combo T3")  + scale_colour_manual(values=clusterColors) + theme_cowplot() + NoLegend() + theme(aspect.ratio = 1, legend.position="right",
                axis.title=element_blank(),
                axis.text=element_blank(),
                axis.ticks=element_blank())

ggsave("pdf/unsup.umap.cluster.comboT3.countour.pdf",width = 5,height = 5)
```


```{r, fig.width=3, fig.height=3, fig.asp=0.6}
ggplot(data.frame(data.seurat.CD8@reductions$umap@cell.embeddings), aes(x=UMAP_1,y=UMAP_2)) + 
  geom_point(aes(color=data.seurat.CD8@meta.data$cluster.lab),alpha=0.4, size=2) + 
  geom_density_2d(data=data.frame(data.seurat.CD8@reductions$umap@cell.embeddings[data.seurat.CD8@meta.data$SampleLabel %in% c("T1-UT","T2-UT"),]), 
                  mapping=aes(x=UMAP_1,y=UMAP_2),color="black",n=100,h=2, size=1) + guides(color=guide_legend(title="CD8 state")) + ggtitle("UT")  + scale_colour_manual(values=clusterColors) + theme_cowplot() + NoLegend() + theme(aspect.ratio = 1, legend.position="right",
                axis.title=element_blank(),
                axis.text=element_blank(),
                axis.ticks=element_blank())

ggsave("pdf/unsup.umap.cluster.UT.countour.pdf",width = 5,height = 5)
```

```{r, fig.width=3, fig.height=3, fig.asp=0.6}
ggplot(data.frame(data.seurat.CD8@reductions$umap@cell.embeddings), aes(x=UMAP_1,y=UMAP_2)) + 
  geom_point(aes(color=data.seurat.CD8@meta.data$cluster.lab),alpha=0.4, size=2) + 
  geom_density_2d(data=data.frame(data.seurat.CD8@reductions$umap@cell.embeddings[data.seurat.CD8@meta.data$SampleLabel=="T2-decoy_mIL2",]), 
                  mapping=aes(x=UMAP_1,y=UMAP_2),color="black",n=100,h=2, size=1) + guides(color=guide_legend(title="CD8 state")) + ggtitle("T2-decoy_mIL2")  + scale_colour_manual(values=clusterColors) + theme_cowplot() + NoLegend() + theme(aspect.ratio = 1, legend.position="right",
                axis.title=element_blank(),
                axis.text=element_blank(),
                axis.ticks=element_blank())

ggsave("pdf/unsup.umap.cluster.mIL2.countour.pdf",width = 5,height = 5)

```


```{r, fig.width=3, fig.height=3, fig.asp=0.6}
ggplot(data.frame(data.seurat.CD8@reductions$umap@cell.embeddings), aes(x=UMAP_1,y=UMAP_2)) + 
  geom_point(aes(color=data.seurat.CD8@meta.data$cluster.lab),alpha=0.4, size=2) + 
  geom_density_2d(data=data.frame(data.seurat.CD8@reductions$umap@cell.embeddings[data.seurat.CD8@meta.data$SampleLabel=="T2-decoy_IL33",]), 
                  mapping=aes(x=UMAP_1,y=UMAP_2),color="black",n=100,h=2, size=1) + guides(color=guide_legend(title="CD8 state")) + ggtitle("T2-decoy_IL33")  + scale_colour_manual(values=clusterColors) + theme_cowplot() + NoLegend() + theme(aspect.ratio = 1, legend.position="right",
                axis.title=element_blank(),
                axis.text=element_blank(),
                axis.ticks=element_blank())

ggsave("pdf/unsup.umap.cluster.IL33.countour.pdf",width = 5,height = 5)
```
Composition barplots
```{r}
to.plot <- subset(data.seurat.CD8, subset=SampleLabel %in% c("T1-UT","T2-UT","T2-combo","T2-decoy_mIL2","T2-decoy_IL33"))
to.plot$Condition <- NA

to.plot$Condition[to.plot$SampleLabel %in% c("T1-UT","T2-UT")] <- "UT"
to.plot$Condition[to.plot$SampleLabel %in% c("T2-decoy_mIL2")] <- "T2-mIL2"
to.plot$Condition[to.plot$SampleLabel %in% c("T2-decoy_IL33")] <- "T2-IL33"
to.plot$Condition[to.plot$SampleLabel %in% c("T2-combo")] <- "T2-combo"
table(to.plot$Condition)

to.plot.list <- SplitObject(to.plot, split.by = "Condition")
states_all <- levels(to.plot$cluster.lab)

m <- matrix(nrow=length(names(to.plot.list)), ncol = length(states_all))
rownames(m) <- names(to.plot.list)
colnames(m) <- states_all
for (i in seq_along(to.plot.list)) {
   tb <- table(factor(to.plot.list[[i]]$cluster.lab, levels = states_all))
   m[i,] <- tb * 100/sum(tb)
}

melt <- reshape2::melt(m)
colnames(melt) <- c("Sample", "CD8_state","Percent")

melt$Sample <- factor(melt$Sample, levels=c("UT","T2-mIL2","T2-IL33","T2-combo"))

p <- ggplot(melt, aes(x = Sample, y = Percent, fill = CD8_state)) + geom_bar(stat = "identity", position = "stack") + 
           scale_fill_manual(values = clusterColors) + theme_light() + theme(legend.position = "right")
p <- p + theme(axis.text.x = element_text(angle = 45, hjust = 1))
p

ggsave("plots/fig2c_barplot_norm.pdf",plot=p, width=3,height=3.5)


```




ProjecTILs analysis


```{r}
ref <- load.reference.map()
data.seurat.CD8.projected <- make.projection(data.seurat.CD8,ref = ref,filter.cells = F)
plot.projection(ref,data.seurat.CD8.projected)
data.seurat.CD8.projected <- cellstate.predict(ref,data.seurat.CD8.projected)
```


```{r}
data.seurat.CD8 <- AddMetaData(data.seurat.CD8,data.seurat.CD8.projected$functional.cluster,col.name="functional.cluster")
table(data.seurat.CD8$functional.cluster)
data.seurat.CD8.sub <- subset(data.seurat.CD8, subset=functional.cluster %in% 
                                c("CD8_NaiveLike","CD8_EffectorMemory","CD8_EarlyActiv","CD8_Tpex","CD8_Tex"))
  
DimPlot(data.seurat.CD8.sub, reduction = "umap", group.by = "functional.cluster") + ggtitle("UMAP by functional cluster")
DimPlot(data.seurat.CD8.sub, reduction = "umap", split.by  = "cluster.lab") + ggtitle("UMAP by unsupervised cluster")
DimPlot(data.seurat.CD8.sub, reduction = "umap", split.by = "functional.cluster", group.by = "cluster.lab") + ggtitle("UMAP by study")
DimPlot(data.seurat.CD8.sub, reduction = "umap", split.by = "cluster.lab", group.by = "functional.cluster") + ggtitle("UMAP by study")
```

```{r fig.height=4}
library(patchwork)
Idents(data.seurat.CD8.projected) <- "cluster.lab"
table(data.seurat.CD8.projected$cluster.lab)
set.seed(1234)
data.seurat.CD8.projected.byCluster <- subset(data.seurat.CD8.projected, cells=WhichCells(data.seurat.CD8.projected, downsample=300))
table(data.seurat.CD8.projected.byCluster$cluster.lab)
data.seurat.CD8.projected.byCluster <- SplitObject(data.seurat.CD8.projected)
plots <- list()
for(c in levels(data.seurat.CD8.projected$cluster.lab)){
  queryObject <- data.seurat.CD8.projected.byCluster[[c]]
  mainState <- names(sort(table(queryObject$functional.cluster),decreasing = T))[1]
  discDim <- find.discriminant.dimensions(ref = ref, query =queryObject,state = mainState,print.n = 6)
  devComp <- sum(discDim$stat_abs[discDim$p_val < 1e-5])
  print(paste(mainState,round(devComp,2)))
  plots[[c]] <- plot.projection(ref,queryObject, linesize = 0.3, pointsize = 0.5) + ggtitle(label = c,subtitle = paste0("Main state",mainState))
}
wplot <- wrap_plots(plots, ncol = 3)
#wplot
ggsave("pdf/projected.umap.by.unsup_cluster.pdf",wplot, width = 15, height = 8)
```


```{r}
plot3d <- plot.discriminant.3d(ref = ref, query.control = data.seurat.CD8.projected.byCluster$C4, query=data.seurat.CD8.projected.byCluster$C5, extra.dim = "ICA_26", query.state = "CD8_Tex")

plot3d

plot3d <- plot.discriminant.3d(ref = ref, query=data.seurat.CD8.projected.byCluster$C5, extra.dim = "ICA_26", query.state = "CD8_Tex")

plot3d
```

Export static figures
```{r}
library(processx)
#Top view
zoom <- 8
plot3d <- plot3d  %>%   layout(scene=list(camera = list(eye = list(x = 0, y = 0, z= 0.25*zoom), up=list(x=0,y=1,z=0))))
plot3d
#orca(plot3d, format="pdf",file="pdf/C5vsC4_ICA25_top.pdf",width = 1200,height = 1200, scale = 2)

#Side view
zoom <- 2
i=pi*4/3
j=0
plot3d <- plot3d  %>% layout(scene=list(camera = list(eye = list(x = cos(i)*zoom, y = sin(i)*zoom, z= cos(j)), up=list(x=0,y=1,z=1) )))
plot3d

orca(plot3d,format="pdf",file="pdf/C5vsref_ICA26_side.pdf",width = 700,height = 600, scale = 3)

```

```{r}
Idents(data.seurat.CD8.projected) <- "Sample"
data.seurat.CD8.projected.samples <- subset(data.seurat.CD8.projected, idents = c("T2-decoy_IL33","T2-decoy_mIL2","T2-UT","T2-combo"))
data.seurat.CD8.projected.samples$T2Combo <- F
data.seurat.CD8.projected.samples$T2Combo[data.seurat.CD8.projected.samples$Sample=="T2-combo"]=T
Idents(data.seurat.CD8.projected.samples) <- "T2Combo"
data.seurat.CD8.projected.samples.T2Combo <- SplitObject(data.seurat.CD8.projected.samples)
plot.discriminant.3d(ref = ref, query.control = data.seurat.CD8.projected.samples.T2Combo[["FALSE"]], query=data.seurat.CD8.projected.samples.T2Combo[["TRUE"]], extra.dim = "ICA_26")
```


```{r}
library(MAST)
Idents(data.seurat.CD8.projected) <- "functional.cluster"
data.seurat.CD8.projected.Tex <- subset(data.seurat.CD8.projected, idents = "CD8_Tex")
Idents(data.seurat.CD8.projected.Tex) <- "cluster.lab"
FeaturePlot(data.seurat.CD8.projected.Tex,features = c("Gzmc","Tox"), split.by = "cluster.lab")
VlnPlot(data.seurat.CD8.projected.Tex,features = c("Tox","Gzmc","Pdcd1"))
DefaultAssay(data.seurat.CD8.projected.Tex) <- "RNA"

markers4vs5 <- FindMarkers(data.seurat.CD8.projected.Tex,ident.1 = "C5",ident.2 = "C4",test.use = "MAST", min.diff.pct = 0.01,logfc.threshold = 0.25, min.pct=0.05, assay="RNA")
```

```{r}
library(EnhancedVolcano)
EnhancedVolcano(markers4vs5,
    lab = rownames(markers4vs5),
    x = 'avg_log2FC',
    y = 'p_val_adj',FCcutoff = 1, drawConnectors = T, maxoverlapsConnectors = 50, pCutoff = 1e-5)
ggsave("pdf/Tex.c4vsc5.volcano.pdf",width = 9,height = 8)

```

```{r}
markers4vs5 <- FindMarkers(data.seurat.CD8.projected.Tex,ident.1 = "C5",ident.2 = "C4",test.use = "MAST", min.diff.pct = 0.01,logfc.threshold = 0.1, min.pct=0.01, assay="RNA")
markers4vs5[rownames(markers4vs5) %in% c("Bcl2","Batf","Bhlhe40") ,]

```
